### ISSUE TITLE
Looking for info on passing request headers and a custom message to mercuriusLogging

### ISSUE THREAD

**Issue by tonyrizzotto** [Eomm/mercurius-logging#17]
Hi! Really like the idea of this package - very helpful!

**Question:**
Not sure if this was intended or not, but request headers don't seem to be passing to the graphql `request.[level]` and I'm trying to figure out: could it be my approach to logging, or if this was intended for some reason?

In my Fastify server, I have `disableRequestLogging: true`, and while I have my own `onRequest` on `onResponse` logging, I'm only passing on the request headers which I receive, which I would like to also be passed on to `mercuriousLogging`. I see no other way to configure to pass on the headers, since the `logGraphQLDetails` function simply logs a `graphql` key.

By default, I'm getting this, with no message (`requestLogging` both true or false makes no difference):

```js
[18:34:59 UTC] INFO:
    request_id: "4d3db65c-698f-44f7-bd87-0038019198d4"
    graphql: {
      "queries": [
        "getAccountDetails"
      ]
    }
```
The expectation here for me would be to see my request headers attached to the request.log:

```js
// mercurius-logging/index.js L47
context.reply.request.log[opts.logLevel]({
    headers: context.reply.request.headers, <-- does the trick
    graphql: {
      queries: queryOps.length > 0 ? queryOps : undefined,
      mutations: mutationOps.length > 0 ? mutationOps : undefined,
      operationName: context.reply.request.body.operationName,
      body: opts.buildBody(context),
      variables: opts.logVariables === true ? context.reply.request.body.variables || null : undefined
    }
  })
}
```

From an observability stand point, it would be nice to be able to provide a unique message, maybe with the operation name:

```js
message: `GraphQL Operation: ${context.reply.request.body.operationName}`
```

... or something like this... but this is so breaking based on how you have your message log configured: msg or message or something else. Fastify/Pino defaults to msg, I think.

For example, I use GCP and Stackdriver requires a message key for messages to pretty-print the log title, otherwise you get an empty log title each time.

Anyway, wondering if you have any insight to the headers thing and if you could see a way forward with the message format topic?
Thanks for the help and work! 👍

**Comment by Eomm** [comment]
Hi, thanks for the issue

I need some time to investigate it, but at first reading it seems reasonable.
I think we can do something more in conjunction with `pino` - need to get the time to play a bit

**Comment by Eomm** [comment]
> The expectation here for me would be to see my request headers attached to the request.log:

I wrote a PR for it - it relies on pino serializer that is the cleanest approach IMHO

> From an observability stand point, it would be nice to be able to provide a unique message, maybe with the operation name:

I think this is another feature request. I don't rely too much on the message field.
