### ISSUE TITLE
This plugin breaks GET requests

### ISSUE THREAD

**Issue by ddeboer** [Eomm/mercurius-logging#22]
The GraphQL spec allows [both GET and POST requests](https://graphql.org/learn/serving-over-http/#get-request), but this line breaks GET requests (where the query is in the query string instead of in the request body):

https://github.com/Eomm/mercurius-logging/blob/e132bc94dfb16b29718db5b2db4d0aa68cd9665b/index.js#L48

Error:

```
Cannot read properties of undefined (reading 'operationName')","stack":"TypeError: Cannot read properties of undefined (reading 'operationName')\n    at logGraphQLDetails (xxx/node_modules/mercurius-logging/index.js:49:52)
```

Should this check be extended to check both request body and query string?

**Comment by Eomm** [comment]
Thanks for reporting!
Yes, I think we forget that use case!

I think the best approach would be to check the `request.method` field and act accordingly.

Would you like to send a Pull Request to address this issue?
