### ISSUE TITLE
Response Time not displaying in Logs

### ISSUE THREAD

**Issue by flowjo-isaach** [Eomm/mercurius-logging#28]
I'm hoping to display the response time for resolved fields and the requests from graphQL. I don't see this information in this module. Is there a configuration I'm missing or does it not exist?

**Comment by Eomm** [comment]
It doesn't exist: this plugin shows what comes in the server and does not count the time each resolver takes.

This plugin's scope is to understand:

- Which query is being used and how much?
- are clients using it in the right way?

so you can drop API or support your customer better and proactively.

For time tracking I suggest:

1. take a look at this plugin instead: https://github.com/nearform/mercurius-explain
2. Group the log data by `reqId`: you have already multiple log lines for a single request. Merging the logline from this plugin and the default fastify response log with the `reqId`, you can get the total request time

**Comment by EDjur** [comment]
Just want to add perhaps a simpler approach,

You can utilize the `logMessage` function and Fastifys built-in `elapsedTime` like so:

```
fastify.register(mercuriusLogging, {
    logMessage: function (context) {
        return `RequestDuration: ${context.reply.elapsedTime}`;
    }
});
```

Unfortunately it'll put the duration under the `message` key in the request, but is great for its simplicity 👍
